config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  get 'products/index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/', to: 'pages#home'

  get 'bags', to: 'bags#index'
  get 'bags/:id', to: 'bags#show', as: :bag

  get 'accessories', to: 'accessories#index'
  get 'accessories/:id', to: 'accessories#show', as: :accessory

  root to: 'pages#home'

  Rails.application.routes.draw do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    get 'products/index'
      get 'bags/:id', to: 'bags#show', as: :name
  end

  Rails.application.routes.draw do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    get 'products/index'
      get 'accessories/:id', to: 'accessories#show'
  end

  Rails.application.routes.draw do
    resources :products, only: [:index]
    resource :cart, only: [:show]
    resources :order_items, only: [:create, :update, :destroy]
    root to: "products#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  ACCESSORIES = {
    1 => { name: "Pearl neckless", material: "Pearl", color: "white", price: "$50" },
    2 => { name: "Chocker", material: "Pearl", color: "black", price: "$70"},
    3 => { name: "Pearl Pendant", material: "Pearl", color: "blue", price: "$100"}
  }

  def index
    if params[:material].blank?
      @accessories = ACCESSORIES
    else
      @accessories = ACCESSORIES.select do |id, a| a[:material] == params[:material]
    end
    end
  end

  def show
    @accessories = ACCESSORIES[params[:id].to_i]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  BAGS = {
    1 => { name: "tote", material: "silicone gel", color: "white", price: "$50" },
    2 => { name: "night purse", material: "genuine leather", color: "black", price: "$70"},
    3 => { name: "blaze", material: "genuine leather", color: "blue", price: "$100"}
  }

  def index
    if params[:material].blank?
      @bags = BAGS
    else
      @bags = BAGS.select do |id, b| b[:material] == params[:material]
    end
    end
  end

  def show
    @bags = BAGS[params[:id].to_i]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def item
  end

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/accessories/index.html.erb
<!-- <div class="container"> -->
  <!-- <div class="form">
    <form action="/accessories" method="get">
      <input type="text" name="material" placeholder="What kind of material?">
      <input type="submit">
    </form>
  </div> -->

 <!--  <% categories = [ 'Pearl' ] %>

  <div class="all">
    <h2>Accessories</h2>

      <ul>
        <% @accessories.each do |id, accessory| %>
          <li>
            <%= link_to accessory[:name], accessory_path(id) %>, <%= accessory[:color] %>,
            <%= accessory[:price] %>, <%= accessory[:material] %>
          </li>
        <% end %>
      </ul>
  </div>
</div> -->


<div class="wrapper">

  <div class="header">
    <h1 class="header__title">Our Accessories</h1>
  </div>

  <div class="cards">

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>
    </div>

  </div>

</div>

app/views/accessories/show.html.erb
<!-- <div class=container>
  <h1> Welcome to: OM Design </h1>
  <h2> <%= @accessories[:name] %> </h2>
  <h3> <%= @accessories[:color] %>, <%= @accessories[:material] %>, <%= @accessories[:price] %> </h3>
</div> -->


  <div class="wrapper">
    <div class="container_item">
      <div class="top">
        <%= image_tag "bag.jpg", alt: "bag photo" %>
        <div class="info">
        </div>
          <div class="bottom">
            <div class="left">
              <div class="details">
                <h1><b><%= @accessories[:name] %></b></h1>
                <p><%= @accessories[:price] %></p>
              </div>
                <div class="buy"><i class="fas fa-shopping-bag"> add to cart</i></div>
                </div>
                  <div class="right">
                    <div class="done"><i class="material-icons">done</i></div>
                      <div class="details">
                        <p>Added to your cart</p>
                      </div>
                        <div class="remove"><i class="material-icons">clear</i></div>
                        </div>
                    </div>
                  </div>
                    <div class="inside">
                      <div class="icon"><i class="material-icons">info</i></div>
                        <div class="contents">
                          <table>
                            <tr>
                              <th>Color</th>
                              <th>Material</th>
                            </tr>
                              <tr>
                                <td><p><%= @accessories[:color] %></td>
                                <td><p><%= @accessories[:material] %></td>
                              </tr>
                          </table>
                        </div>
                      </div>
                    </div>
            </div>
          </div>
      </div>
    </div>
  </div>

app/views/bags/index.html.erb
<!-- <div class="container">
  <div class="form">
    <form action="/bags" method="get">
      <input type="text" name="material" placeholder="What kind of material?">
      <input type="submit">
    </form>
  </div>

  <% categories = [ 'Genuine leather', 'Silicone gel' ] %> -->

  <!-- <div class="all">
      <ul>
        <% @bags.each do |id, bag| %>
          <li>
            <%= link_to bag[:name], bag_path(id) %>, <%= bag[:color] %>,
            <%= bag[:price] %>, <%= bag[:material] %>
          </li>
        <% end %>
      </ul>
  </div>
</div> -->

<div class="wrapper">

  <div class="header">
    <h1 class="header__title">Our Bags</h1>
  </div>

  <div class="cards">

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    </div>

  </div>

</div>

<!-- <h2>Categories</h2>
    <ul>
      <% categories.each do |category| %>
        <li><%= category.capitalize %></li>
        <% end %>
    </ul> -->

app/views/bags/show.html.erb
<!-- <div class=container>
  <div class="card">
    <%= image_tag "bag.jpg", alt: "bag photo" %>
  <div class="info">
    <h4><b><%= @bags[:name] %></b></h4>
    <p><%= @bags[:color] %></p>
    <p><%= @bags[:material] %></p>
    <p><%= @bags[:price] %></p>
  </div>
  </div>
</div> -->
<div class="container">
  <div class="wrapper">
    <div class="container_item">
      <div class="top">
        <%= image_tag "bag.jpg", alt: "bag photo" %>
        <div class="info">
        </div>
          <div class="bottom">
            <div class="left">
              <div class="details">
                <h1><b><%= @bags[:name] %></b></h1>
                <p><%= @bags[:price] %></p>
              </div>
                <div class="buy"><i class="fas fa-shopping-bag"> add to cart</i></div>
                </div>
                  <div class="right">
                    <div class="done"><i class="material-icons">done</i></div>
                      <div class="details">
                        <p>Added to your cart</p>
                      </div>
                        <div class="remove"><i class="material-icons">clear</i></div>
                        </div>
                    </div>
                  </div>
                    <div class="inside">
                      <div class="icon"><i class="material-icons">info</i></div>
                        <div class="contents">
                          <table>
                            <tr>
                              <th>Color</th>
                              <th>Material</th>
                            </tr>
                              <tr>
                                <td><p><%= @bags[:color] %></td>
                                <td><p><%= @bags[:material] %></td>
                              </tr>
                          </table>
                        </div>
                      </div>
                    </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<div class= "container">
  <% if !@order_item.nil? && @order_item.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @order_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
    <% if @order_items.size == 0 %>
    <div id="text-center">
      No items added. <br><%= link_to "Keep shopping", root_path %> </br>
    </div>
    <% else %>
      <% @order_items.each do |order_item| %>
        <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
      <% end %>
    <% end %>
</div>

app/views/carts/show.html.erb
<div class="wrapper">
    <div id="shopping-cart">
      <h2>Your Cart</h2>
      <%= render "shopping_cart" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>OM Design</title>

    <meta name="description" content="Fashionable bags & accessories at amazing prices.">
    <meta property="og:title" content="OM Design - Fashionable bags at amazing prices">
    <meta property="og:image" content="facebook-card.jpg">
    <meta property="og:description" content="OM Design stirves to bring you the latest designs to keep you looking amazing.">
    <meta property="og:site_name" content="OM Design"/>

    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>

    <style>
      a { color: #00CED1; } /* CSS link color */
    </style>

    <div id="nav-logo">
      <%= image_tag "omlogo.png", alt: "OM Logo", height: 100; %>
      <h3> OM Design </h3>
        <div id ="cart_qty">
          <%= link_to "#{current_order.order_items.size} Items in Cart", cart_path, class: "btn btn-link" %>
        </div>
    </div>

  <body>
    <%= yield %>
      <div class="container">
        <div class="row">
          <div class="col-xs-6 text-right">
            <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
          </div>
        </div>
      </div>
  </body>

  <footer>
    <div id="footer-media">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>

    <div class="footer-links">
      <%= link_to "Know more about us", about_path %>
      <%= link_to "Discover all our bags", bags_path %>
      <%= link_to "Discover all our Accessories", accessories_path %>
      <%= link_to "Contact us", contact_path %>
    </div>
  </footer>

</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/udpate.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/pages/about.html.erb
<div class="wrapper">
  <div class="about_info">

    <h1>OM Design</h1>

    <body>
      <%= image_tag "omlogo.png", alt: "OM Logo"%>
    </body>

    <p>Description about us.</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="wrapper">
  <div class="contact_info">
    <h1> Welcome to: OM Design </h1>
    <p>Montenegro #+31</p>
  </div>
</div>

app/views/pages/home.html.erb
<!-- <div class="form">
  <form action="/bags" method="get">
    <input type="text" name="material" placeholder="What kind of material?">
    <input type="submit">
  </form>
</div> -->

<div class="wrapper">

  <div class="header">
    <h1 class="header__title">Bags & Accessories</h1>
  </div>

  <div class="cards">

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
        <span>Card</span>
        <i class="fa fa-folder-o"></i>
      </div>
      <div class="card__expander">
        <i class="fa fa-close [ js-collapser ]"></i>
        Expander
      </div>
    </div>
    </div>

  </div>

</div>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>